/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package peluquero;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setTextFieldChanged(nChairsTextBox);
        InicioButton.setEnabled(false);
        FinalizarButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        progressCut = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        waitingList = new javax.swing.JList();
        estadobarberoLabel = new javax.swing.JLabel();
        estadobarbero = new javax.swing.JLabel();
        estadosillaLabel = new javax.swing.JLabel();
        estadosilla = new javax.swing.JLabel();
        nChairsTextBox = new javax.swing.JTextField();
        InicioButton = new javax.swing.JButton();
        FinalizarButton = new javax.swing.JButton();
        nChairsLabel = new javax.swing.JLabel();
        waitingLabel1 = new javax.swing.JLabel();
        waitingLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        container.setBackground(new java.awt.Color(255, 204, 102));

        waitingList.setModel(model);
        jScrollPane1.setViewportView(waitingList);

        estadobarberoLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        estadobarberoLabel.setText("Estado Barbero:");

        estadobarbero.setText("...");

        estadosillaLabel.setText("En silla:");

        estadosilla.setText("...");

        InicioButton.setText("Inicio");
        InicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioButtonActionPerformed(evt);
            }
        });

        FinalizarButton.setText("Finalizar");
        FinalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarButtonActionPerformed(evt);
            }
        });

        nChairsLabel.setText("Numero de silla:");

        waitingLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        waitingLabel1.setText("El barbero Dormilón");

        org.jdesktop.layout.GroupLayout containerLayout = new org.jdesktop.layout.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containerLayout.createSequentialGroup()
                .add(17, 17, 17)
                .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(containerLayout.createSequentialGroup()
                        .add(waitingLabel1)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(containerLayout.createSequentialGroup()
                        .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(containerLayout.createSequentialGroup()
                                .add(estadobarberoLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(estadobarbero))
                            .add(containerLayout.createSequentialGroup()
                                .add(estadosillaLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(estadosilla))
                            .add(containerLayout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(progressCut, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(containerLayout.createSequentialGroup()
                                        .add(nChairsLabel)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(nChairsTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 141, Short.MAX_VALUE)
                        .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, containerLayout.createSequentialGroup()
                                .add(InicioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(FinalizarButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, containerLayout.createSequentialGroup()
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(37, 37, 37))))))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, containerLayout.createSequentialGroup()
                .add(21, 21, 21)
                .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(containerLayout.createSequentialGroup()
                        .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(estadobarberoLabel)
                            .add(estadobarbero))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(estadosillaLabel)
                            .add(estadosilla))
                        .add(18, 18, 18)
                        .add(progressCut, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                .add(containerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nChairsLabel)
                    .add(nChairsTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(InicioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(FinalizarButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(waitingLabel1)
                .add(51, 51, 51))
        );

        waitingLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        waitingLabel.setText("CLIENTES EN ESPERA:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(container, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(waitingLabel)
                .add(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(waitingLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(container, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void InicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioButtonActionPerformed
        // TODO add your handling code here:
        
        //numero de sillas
        try{
            Integer.parseInt(nChairsTextBox.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid number");
            return;
        }
        
        final int numeroSillas  = Integer.parseInt(nChairsTextBox.getText());
      
        //Monitor
        final control m = new control(numeroSillas, estadobarbero, model, estadosilla, progressCut);
        
        //Barbero
        final Barbero barbero = new Barbero(m, estadobarbero, estadosilla, progressCut);
        
        List<Cliente> clientes = new ArrayList<Cliente>();
        
        
        //se inicializan los hilso del monitor y del barbero.
        new Thread(barbero).start();
        new Thread(m).start();
        
        //habilitar los botones
        InicioButton.setEnabled(false);
        FinalizarButton.setEnabled(true);
        
        //inicializar clientes
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    int numCliente=0;
                    Random r = new Random();
                    while(true){
                        Thread.sleep(r.nextInt(10000));
                        if(m.clientesEspera<numeroSillas){
                            Cliente nuevo = new Cliente(m, barbero, model, estadobarbero, ++numCliente);
                            Thread t = new Thread(nuevo);
                            t.start();
                        }else{
                            System.out.println("Llego un cliente y se fue");
                        }
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start(); 
    }//GEN-LAST:event_InicioButtonActionPerformed

    private void FinalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarButtonActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_FinalizarButtonActionPerformed

    private void setTextFieldChanged(JTextField txt){
        final JTextField t = txt;
        DocumentListener documentListener = new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent de) {
                changeEnabled(de);
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                changeEnabled(de);
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                changeEnabled(de);
            }
        };
        txt.getDocument().addDocumentListener(documentListener);
    }
    
    private void changeEnabled(DocumentEvent event){
        DocumentEvent.EventType type = event.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE)){
 
        }
        else if (type.equals(DocumentEvent.EventType.INSERT)){
            if(nChairsTextBox.getText().length()>0){
                InicioButton.setEnabled(true);
            }
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE)){
           if(nChairsTextBox.getText().length()==0){
                InicioButton.setEnabled(false);
            } 
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinalizarButton;
    private javax.swing.JButton InicioButton;
    private javax.swing.JPanel container;
    private javax.swing.JLabel estadobarbero;
    private javax.swing.JLabel estadobarberoLabel;
    private javax.swing.JLabel estadosilla;
    private javax.swing.JLabel estadosillaLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nChairsLabel;
    private javax.swing.JTextField nChairsTextBox;
    private javax.swing.JProgressBar progressCut;
    private javax.swing.JLabel waitingLabel;
    private javax.swing.JLabel waitingLabel1;
    private javax.swing.JList waitingList;
    private DefaultListModel model = new DefaultListModel();
    // End of variables declaration//GEN-END:variables
}
